services:
  db:
    image: postgres:latest
    container_name: movie-review-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretsanta0123
      POSTGRES_DB: movie_review_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - ./user-service/.env  
      # Specify the correct path to the .env file
    volumes:
      - ./user-service:/app

  movie-service:
    build: ./movie-service
    container_name: movie-service
    ports:
      - "8002:8000"
    depends_on:
      - db
    env_file:
      - ./movie-service/.env # Specify the correct path to the .env file
    volumes:
      - ./movie-service:/app

  review-service:
    build: ./review-service
    container_name: review-service
    ports:
      - "8003:8000"
    depends_on:
      - db
    env_file:
      - ./review-service/.env # Specify the correct path to the .env file
    volumes:
      - ./review-service:/app

volumes:
  postgres_data: