
services:
  db:
    image: postgres:latest
    container_name: movie-review-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./user-service:/app

  movie-service:
    build: ./movie-service
    container_name: movie-service
    ports:
      - "8002:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./movie-service:/app

  review-service:
    build: ./review-service
    container_name: review-service
    ports:
      - "8003:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./review-service:/app

volumes:
  postgres_data:
