global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:8001']

  - job_name: 'movie-service'
    static_configs:
      - targets: ['host.docker.internal:8002']

  - job_name: 'review-service'
    static_configs:
      - targets: ['host.docker.internal:8003']