apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: docker.io/library/review-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          command: ["uvicorn"]
          args: ["app:app", "--host", "0.0.0.0", "--port", "8000"]
          envFrom:
            - configMapRef:
                name: movie-review-config