apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: docker.io/library/user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          command: ["uvicorn"]
          args: ["app:app", "--host", "0.0.0.0", "--port", "8000"]
          envFrom:
            - configMapRef:
                name: movie-review-config
          env:
            - name: SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: movie-review-config
                  key: SECRET_KEY
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movie-review-secret
                  key: POSTGRES_PASSWORD