name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: movie_review_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: secretsanta0123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set environment variables
      run: |
        echo "POSTGRES_DB=movie_review_db" >> $GITHUB_ENV
        echo "POSTGRES_USER=admin" >> $GITHUB_ENV
        echo "POSTGRES_PASSWORD=secretsanta0123" >> $GITHUB_ENV
        echo "POSTGRES_HOST=db" >> $GITHUB_ENV
        echo "POSTGRES_PORT=5432" >> $GITHUB_ENV
        echo "SECRET_KEY=testsecretkey" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Start Microservices
      run: docker compose up -d --build

    - name: Wait for services to be ready
      run: sleep 25

    - name: Run tests inside test-runner container
      run: docker exec test-runner bash -c "source venv/bin/activate && pytest -v"

    - name: Tear down containers
      if: always()
      run: docker compose down