name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: movie_review_db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: secretsanta0123
       # ports:
       #   - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set environment variables
      run: |
        echo "POSTGRES_USER=admin" >> $GITHUB_ENV
        echo "POSTGRES_PASSWORD=secretsanta0123" >> $GITHUB_ENV
        echo "POSTGRES_DB=movie_review_db" >> $GITHUB_ENV
        echo "POSTGRES_HOST=db" >> $GITHUB_ENV
        echo "POSTGRES_PORT=5432" >> $GITHUB_ENV
        echo "SECRET_KEY=secretsanta" >> $GITHUB_ENV
        echo "DATABASE_URL=postgresql://admin:secretsanta0123@db:5432/movie_review_db" >> $GITHUB_ENV
        echo "BASE_URL=http://user-service:8000" >> $GITHUB_ENV

    - name: Start all microservices
      run: docker compose up -d --build

    - name: Show logs for user-service
      run: docker logs user-service || true

    - name: Wait for services to be ready
      run: |
        echo "Waiting for user-service to be ready..."
        for i in {1..15}; do
          docker logs user-service 2>&1 | grep -q "Uvicorn running" && break
          sleep 5
        done

    - name: Run tests from user-service
      run: docker exec user-service pytest -v

    - name: Tear down
      run: docker compose down